---
title: "Aggregated_Models"
output: html_document
date: "2023-10-13"
knit: (function(inputFile, encoding) { 
      out_dir <- 'Rmarkdowns';
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), out_dir, 'MainFileProjection.html')) })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(openxlsx)
library(readxl)
library(tidyverse)
library(ggplot2)
library(gridExtra)
library(randomForest)
library(glmnet)
library(cowplot)
library(Boruta) #Feature selection
library(boot)
library(xgboost)
library(grid)
library(IRdisplay)
library(cowplot)
library(boot)
library(caret)
library(mboost)
library(ranger)
library(gam)
library(parallel)
```

### Import Functions

```{r echo=FALSE, message=FALSE, warning=FALSE}

# === Import Functions ==================== #

# Models
source("Functions/Modeling/RandomForest.R")
source("Functions/Modeling/Lasso.R")
source("Functions/Modeling/XGBoost.R")
source("Functions/Modeling/Boost_glm.R")
source("Functions/Modeling/Boost_gam.R")
source("Functions/Modeling/RFRanger.R")
#source("Functions/Modeling/gamSpline.R")


# Metrics Estimation MAE and RMED
source("Functions/Results/Est_Metrics.R")

# Confident Intervals
source("Functions/Results/ConfidentIntervalGeneral.R")

# Plot Results
source("Functions/Results/PlotResultsGeneral.R")

# Get All Results
source("Functions/Results/GetResultsGeneral.R")

```

# Read Data and Compute Aggregate Data

```{r echo=FALSE, message=FALSE, warning=FALSE}
population_variable <- "SOC5"
Imputed_data_0 <- as.data.frame(
  read.xlsx("./Imputed_data/Final_imputed_data_All_with_Regions.xlsx"))
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
Imputed_data <- Imputed_data_0[, c("Country",
                                   "Indicator",
                                   "Year",
                                   "Value")]
# Population Data
pop_data <- Imputed_data[Imputed_data$Indicator == "SOC5",
                         c("Country", "Year", "Value")]

pop_data <- pop_data[,c("Country", "Year", "Value")]
colnames(pop_data) <- c("Country", "Year", "Population")
total_pop <- pop_data %>% group_by(Year) %>%
  summarise(TotalPop=sum(Population), .groups = 'drop')
pop_data <- merge(pop_data, total_pop, by.x=c("Year"),
                  by.y=c("Year"), all.x=TRUE)
pop_data$PopWeight <- pop_data$Population/pop_data$TotalPop

var_data <- Imputed_data[Imputed_data$Indicator != "SOC5", ]
variables_ <- unique(var_data$Indicator)

Aggregate_Data <- data.frame()
    
for (var in variables_) {
  
  # cat(paste("Processing ", var, " ... \n"))
  
  indicator_data <- var_data[which(var_data$Indicator == var), ]
  indicator_data <- merge(indicator_data, pop_data, by.x=c("Country", "Year"),
                          by.y=c("Country", "Year"), all.x=TRUE)
  
  indicator_data$WeightedValueRaw <- indicator_data$Value * indicator_data$PopWeight
  indicator_data <- na.omit(indicator_data)
  
  Aggregate_Data_Indicator <- indicator_data %>% group_by(Year) %>%
    summarise(MedianValue=median(Value),
              WeightedValue=sum(WeightedValueRaw),
              MeanValue=mean(Value), .groups = 'drop')
  
  Aggregate_Data_Indicator$Indicator <- var
  Aggregate_Data <- rbind(Aggregate_Data, Aggregate_Data_Indicator)
}

Aggregate_Data$Region <- 'Americas'

write.xlsx(Aggregate_Data, "./Imputed_Data/Aggregate_Data_Americas.xlsx")
```

# Compute best models for Americas (using all data available)

```{r echo=FALSE, message=FALSE, warning=FALSE}

value_col_to_use <- "WeightedValue" # MedianValue, MeanValue
indicators <- c("SUICF", "CovIndex", "SUICM")
region_cols <- c("Region")

Aggregate_Data_Use_All <- as.data.frame(
  read.xlsx("./Imputed_Data/Aggregate_Data_Americas.xlsx"))

for (Outcome_name in indicators) {
  
  cat(paste("Model creation for ", Outcome_name, "\n"))
  
  Aggregate_Data_Use <- Aggregate_Data_Use_All[,
                                               c("Year", "Region",
                                                 "Indicator", value_col_to_use)]
  colnames(Aggregate_Data_Use) <-c("Year", "Region",
                                   "Indicator", "Value")
  
  Aggregate_Data_Use$Indicator[
    which(Aggregate_Data_Use$Indicator== Outcome_name)] <- "Outcome"
  
  if (Outcome_name == "CovIndex"){
    ind_suicf <- which(Aggregate_Data_Use$Indicator=="SUICF")
    ind_suicm <- which(Aggregate_Data_Use$Indicator=="SUICM")
    Aggregate_Data_Use <-Aggregate_Data_Use[-c(ind_suicf,ind_suicm),]
  }else{
    ind_CovIndex <-which(Aggregate_Data_Use$Indicator=="CovIndex")
    ind_dma <- which(Aggregate_Data_Use$Country=="DMA"|Aggregate_Data_Use$Country=="KNA")
    if (Outcome_name=="SUICF"){
      ind_suic <- which(Aggregate_Data_Use$Indicator=="SUICM")
    }else{
      ind_suic <- which(Aggregate_Data_Use$Indicator=="SUICF")}
    Aggregate_Data_Use <- Aggregate_Data_Use[-c(ind_suic,ind_dma,ind_CovIndex),]
  }

  set.seed(123)
  Data_used <- Aggregate_Data_Use
  
  # Identify the total regions in the file
  list_of_regions <- unique(Data_used$Region)            
  list_of_figures           <-list()  # Save the prediction for each region
  list_of_relevant_var      <-list()  # Save selected variables
  list_of_final_prediction  <-list()
  
  info_df <- data.frame()
  list_of_metrics_by_region <- data.frame()
  
  for(region in list_of_regions){
    
    tryCatch({
      
      # Decide if you want to add hyper parameter tuning or cross validation
      # to the model fit
      hyper_tune <- TRUE
      cv         <- TRUE
      
      # get results but using all data for training (use_all parameter)
      results_region <- get_results(region, "Region", Data_used,
                                    hyper_tune, cv, Outcome_name,
                                    use_all=TRUE, add_fit=FALSE)

      # general info
      info_df <- rbind(info_df, results_region$info_df_)
      
      #figures
      list_of_figures[[region]] <- results_region$figure_[[1]]
      
      #save metrics  
      final_metrics = results_region$metrics_ 
      final_metrics$region = region
      
      list_of_metrics_by_region<-rbind(list_of_metrics_by_region,
                                       final_metrics)
      
      #save predictions to plot later
      list_of_final_prediction[[region]]<-results_region$figure_[[2]]
      
    }, error = function(err){
      cat(paste("Error computing results for", region, err, "\n"))
    })
    
  }

  # Create a list of plots using your figures
  plot_list <- lapply(names(list_of_figures), function(obj_name) {
    figure  <- list_of_figures[[obj_name]]
    # Add the title equal to the object's name
    figure +
      theme_bw() +
      labs(x = "", y = "", subtitle = obj_name)
  })

  ncol_ = 3
  nrow_ = 3
  
  # Arrange the plots in a grid using plot_grid
  grid_plot <- plot_grid(plotlist=plot_list, nrow=nrow_ , ncol=ncol_)
  
  # Display the grid of figures
  figure <- grid_plot
  ggsave(paste("./Figures/Region_Results/All_Predictions",
               Outcome_name, "Americas.pdf", sep="_"),
         figure, width = 15, height = 20) 
  result_list <- list(
    "Model_Info"= info_df,
    "Metrics"   = list_of_metrics_by_region)
  
  write.xlsx(result_list, paste("./Figures/Region_Results/Relevant_var",
                                Outcome_name,
                                "Americas.xlsx", sep="_"))

  write.xlsx(list_of_final_prediction,
             paste("./Figures/Region_Results/Final_predictions",
                   Outcome_name,
                   "Americas.xlsx", sep="_"))
}
```




